CREATE TABLE conta (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    data_vencimento DATE NOT NULL,
    data_pagamento DATE,
    valor DECIMAL(10, 2) NOT NULL,
    valor_pago DECIMAL(10, 2),
    descricao VARCHAR(255) NOT NULL,
    situacao VARCHAR(50) NOT NULL
);
